apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
    mongo-root-username: dXNlcm5hbWU=
    mongo-root-password: cGFzc3dvcmQ=
    mongo-auth-username: dXNlcm5hbWU=
    mongo-auth-password: cGFzc3dvcmQ=
